/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2;

import javax.swing.JOptionPane;
import java.lang.Math;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author elkalilusha
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        pt1BaseLabel.setVisible(false);
        pt1AlturaLabel.setVisible(false);
        pt1BaseTextField.setVisible(false);
        pt1AlturaTextField.setVisible(false);
        pt1ResultButton.setVisible(false);
        pt1RadioLabel.setVisible(false);
        pt1RadioTextField.setVisible(false);
        pt31LimLabel.setVisible(false);
        pt31TextFiel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programacionMainFrame = new javax.swing.JTabbedPane();
        programacion = new javax.swing.JTabbedPane();
        programasSecuenciales = new javax.swing.JTabbedPane();
        pt1Ejercicio1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pt1ComboBox = new javax.swing.JComboBox<>();
        pt1ComboBoxbtn = new javax.swing.JButton();
        pt1AlturaLabel = new javax.swing.JLabel();
        pt1BaseLabel = new javax.swing.JLabel();
        pt1AlturaTextField = new javax.swing.JTextField();
        pt1BaseTextField = new javax.swing.JTextField();
        pt1ResultButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pt1RadioLabel = new javax.swing.JLabel();
        pt1RadioTextField = new javax.swing.JTextField();
        pt1CheckBox = new javax.swing.JCheckBox();
        pt1Ejercicio2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pt2TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pt1Ejercicio3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pt3TextArea = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        pt1Ejercicio4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pt4Label = new javax.swing.JTextField();
        pt4Button = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pt1Ejercicio5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        programasCondicionales = new javax.swing.JTabbedPane();
        pt2Ejercicio1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ptt1TextField1 = new javax.swing.JTextField();
        ptt1TextField2 = new javax.swing.JTextField();
        ptt1TextField3 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        pt2Ejercicio2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pt22Button1 = new javax.swing.JButton();
        ptt22TextField1 = new javax.swing.JComboBox<>();
        pt2Ejercicio3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pt23TextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pt23Button1 = new javax.swing.JButton();
        pt2Ejercicio4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pt25TextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        programasRepetitivos = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pt31LimLabel = new javax.swing.JLabel();
        pt31TextField1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        pt31TextFiel2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pt31CheckBox = new javax.swing.JCheckBox();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prueba = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pt32TextField1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtField1 = new javax.swing.JTextField();
        jButtonParImpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        textField1 = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        arreglos = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        arrt1TextField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        arrt1Button1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        poo = new javax.swing.JTabbedPane();
        jButton4 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Área de un triángulo y círculo");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Escoge la figura");

        pt1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Triángulo", "Círculo" }));

        pt1ComboBoxbtn.setText("Aceptar");
        pt1ComboBoxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt1ComboBoxbtnActionPerformed(evt);
            }
        });

        pt1AlturaLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        pt1AlturaLabel.setText("Altura");

        pt1BaseLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        pt1BaseLabel.setText("Base");

        pt1ResultButton.setText("Resultado");
        pt1ResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt1ResultButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pt1RadioLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        pt1RadioLabel.setText("Radio");

        pt1CheckBox.setText("Punto Decimal");

        javax.swing.GroupLayout pt1Ejercicio1Layout = new javax.swing.GroupLayout(pt1Ejercicio1);
        pt1Ejercicio1.setLayout(pt1Ejercicio1Layout);
        pt1Ejercicio1Layout.setHorizontalGroup(
            pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(pt1ComboBoxbtn))
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pt1CheckBox)
                            .addComponent(pt1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                                .addComponent(pt1AlturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(pt1RadioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                                .addComponent(pt1AlturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pt1RadioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(pt1BaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pt1BaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(pt1ResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164))))
        );
        pt1Ejercicio1Layout.setVerticalGroup(
            pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pt1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pt1Ejercicio1Layout.createSequentialGroup()
                        .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pt1AlturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pt1BaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pt1RadioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pt1AlturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pt1BaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pt1RadioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pt1Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pt1ResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt1ComboBoxbtn))
                .addGap(31, 31, 31)
                .addComponent(pt1CheckBox)
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        programasSecuenciales.addTab("Ejercicio 1", pt1Ejercicio1);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setText("Longitud de una cadena de caracteres");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Ingresa Texto");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pt1Ejercicio2Layout = new javax.swing.GroupLayout(pt1Ejercicio2);
        pt1Ejercicio2.setLayout(pt1Ejercicio2Layout);
        pt1Ejercicio2Layout.setHorizontalGroup(
            pt1Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio2Layout.createSequentialGroup()
                .addGroup(pt1Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt1Ejercicio2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel3))
                    .addGroup(pt1Ejercicio2Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(pt1Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pt2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pt1Ejercicio2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        pt1Ejercicio2Layout.setVerticalGroup(
            pt1Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(27, 27, 27))
        );

        programasSecuenciales.addTab("Ejercicio 2", pt1Ejercicio2);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Mostrar Random (Numero aleatorio del 0 al 10)");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Generar numero aleatorio");

        pt3TextArea.setEditable(false);
        pt3TextArea.setBackground(new java.awt.Color(191, 181, 110));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pt1Ejercicio3Layout = new javax.swing.GroupLayout(pt1Ejercicio3);
        pt1Ejercicio3.setLayout(pt1Ejercicio3Layout);
        pt1Ejercicio3Layout.setHorizontalGroup(
            pt1Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pt1Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(pt1Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                        .addComponent(pt3TextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))))
        );
        pt1Ejercicio3Layout.setVerticalGroup(
            pt1Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pt3TextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(36, 36, 36))
        );

        programasSecuenciales.addTab("Ejercicio 3", pt1Ejercicio3);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel7.setText("Raíz cuadrada de ‘n’ numero");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Ingresa un numero");

        pt4Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt4LabelActionPerformed(evt);
            }
        });

        pt4Button.setText("Ok");
        pt4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt4ButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pt1Ejercicio4Layout = new javax.swing.GroupLayout(pt1Ejercicio4);
        pt1Ejercicio4.setLayout(pt1Ejercicio4Layout);
        pt1Ejercicio4Layout.setHorizontalGroup(
            pt1Ejercicio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio4Layout.createSequentialGroup()
                .addGroup(pt1Ejercicio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt1Ejercicio4Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel7))
                    .addGroup(pt1Ejercicio4Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(pt4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pt1Ejercicio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio4Layout.createSequentialGroup()
                        .addComponent(pt4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt1Ejercicio4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        pt1Ejercicio4Layout.setVerticalGroup(
            pt1Ejercicio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pt4Button)
                .addGap(51, 51, 51)
                .addComponent(jButton7)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        programasSecuenciales.addTab("Ejercicio 4", pt1Ejercicio4);

        jLabel9.setText("Mostrar cuantos caracteres tiene una cadena");

        javax.swing.GroupLayout pt1Ejercicio5Layout = new javax.swing.GroupLayout(pt1Ejercicio5);
        pt1Ejercicio5.setLayout(pt1Ejercicio5Layout);
        pt1Ejercicio5Layout.setHorizontalGroup(
            pt1Ejercicio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio5Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        pt1Ejercicio5Layout.setVerticalGroup(
            pt1Ejercicio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt1Ejercicio5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        programasSecuenciales.addTab("Ejercicio5", pt1Ejercicio5);

        programacion.addTab("Programas Secuenciales", programasSecuenciales);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel10.setText(" El Mayor de 3 números");

        jButton8.setText("Aceptar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pt2Ejercicio1Layout = new javax.swing.GroupLayout(pt2Ejercicio1);
        pt2Ejercicio1.setLayout(pt2Ejercicio1Layout);
        pt2Ejercicio1Layout.setHorizontalGroup(
            pt2Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt2Ejercicio1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(pt2Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pt2Ejercicio1Layout.createSequentialGroup()
                        .addComponent(ptt1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(pt2Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pt2Ejercicio1Layout.createSequentialGroup()
                                .addComponent(ptt1TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(ptt1TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        pt2Ejercicio1Layout.setVerticalGroup(
            pt2Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt2Ejercicio1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addGroup(pt2Ejercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptt1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptt1TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptt1TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        programasCondicionales.addTab("Ejercicio 1", pt2Ejercicio1);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setText("Etapas de vida");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel12.setText("Ingresa tu edad");

        pt22Button1.setText("Ok");
        pt22Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt22Button1ActionPerformed(evt);
            }
        });

        ptt22TextField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Mayor a 60", "Mayor a 26", "Mayor a 17", "Mayor a 11", "Mayor a 4", "Menor a 4" }));

        javax.swing.GroupLayout pt2Ejercicio2Layout = new javax.swing.GroupLayout(pt2Ejercicio2);
        pt2Ejercicio2.setLayout(pt2Ejercicio2Layout);
        pt2Ejercicio2Layout.setHorizontalGroup(
            pt2Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt2Ejercicio2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pt2Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pt2Ejercicio2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(257, 257, 257))
            .addGroup(pt2Ejercicio2Layout.createSequentialGroup()
                .addGroup(pt2Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt2Ejercicio2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(pt22Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pt2Ejercicio2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(ptt22TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        pt2Ejercicio2Layout.setVerticalGroup(
            pt2Ejercicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt2Ejercicio2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptt22TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(pt22Button1)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        programasCondicionales.addTab("Ejercicio 2", pt2Ejercicio2);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel13.setText("De numero a palabra");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setText("Ingresa un numero");

        pt23Button1.setText("Aceptar");
        pt23Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt23Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pt2Ejercicio3Layout = new javax.swing.GroupLayout(pt2Ejercicio3);
        pt2Ejercicio3.setLayout(pt2Ejercicio3Layout);
        pt2Ejercicio3Layout.setHorizontalGroup(
            pt2Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pt2Ejercicio3Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(pt2Ejercicio3Layout.createSequentialGroup()
                .addGroup(pt2Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pt2Ejercicio3Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel17))
                    .addGroup(pt2Ejercicio3Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(pt2Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pt23TextField1)
                            .addComponent(pt23Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pt2Ejercicio3Layout.setVerticalGroup(
            pt2Ejercicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt2Ejercicio3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pt23TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt23Button1)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        programasCondicionales.addTab("Ejercicio 3", pt2Ejercicio3);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel14.setText("Estado Civil");

        javax.swing.GroupLayout pt2Ejercicio4Layout = new javax.swing.GroupLayout(pt2Ejercicio4);
        pt2Ejercicio4.setLayout(pt2Ejercicio4Layout);
        pt2Ejercicio4Layout.setHorizontalGroup(
            pt2Ejercicio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt2Ejercicio4Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        pt2Ejercicio4Layout.setVerticalGroup(
            pt2Ejercicio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pt2Ejercicio4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        programasCondicionales.addTab("Ejercicio 4", pt2Ejercicio4);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel15.setText("Mostrar letras \"J\"");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel16.setText("Ingresa Texto");

        pt25TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt25TextField1ActionPerformed(evt);
            }
        });

        jButton9.setText("Ok");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pt25TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pt25TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton9)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        programasCondicionales.addTab("Ejercicio 5", jPanel5);

        programacion.addTab("Programas Condicionales", programasCondicionales);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel18.setText("La tabla de multiplicar de ‘n’ número");

        pt31LimLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        pt31LimLabel.setText("Ingresa un limite");

        jButton10.setText("Aceptar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        pt31TextFiel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt31TextFiel2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel20.setText("Ingresa un numero");

        pt31CheckBox.setText("Ingresar un limite");

        jButton11.setText("Aceptar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        prueba.setEditable(false);
        prueba.setColumns(20);
        prueba.setRows(5);
        jScrollPane1.setViewportView(prueba);

        jButton13.setText("Limpiar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pt31TextFiel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(pt31LimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pt31CheckBox)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pt31TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt31LimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt31TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt31TextFiel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt31CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        programasRepetitivos.addTab("Ejercicio 1", jPanel11);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel19.setText("Años bisiestos ");

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButton12))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(pt32TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pt32TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        programasRepetitivos.addTab("Ejercicio 2", jPanel12);

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel21.setText(" Números pares e impares de 0 a ‘n’ numero");

        txtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField1ActionPerformed(evt);
            }
        });

        jButtonParImpar.setText("Resultado");
        jButtonParImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParImparActionPerformed(evt);
            }
        });

        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        jScrollPane2.setViewportView(txtArea1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonParImpar)
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap(139, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addGap(129, 129, 129))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel21)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonParImpar)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        programasRepetitivos.addTab("Ejercicio 3", jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        programasRepetitivos.addTab("Ejercicio 4", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        programasRepetitivos.addTab("Ejercicio 5", jPanel15);

        programacion.addTab("Programas Repetitivos", programasRepetitivos);

        arrt1TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrt1TextField1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel22.setText("Cuantos numeros deseas capturar");

        arrt1Button1.setText("Aceptar");
        arrt1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrt1Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel22))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrt1Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrt1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrt1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrt1Button1)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        arreglos.addTab("Ejercicio 1", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        arreglos.addTab("Ejercicio 2", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        arreglos.addTab("Ejercicio 3", jPanel10);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        arreglos.addTab("Ejercicio 4", jPanel16);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        arreglos.addTab("Ejercicio 5", jPanel17);

        programacion.addTab("Arreglos", arreglos);
        programacion.addTab("POO", poo);

        jButton4.setText("jButton4");
        programacion.addTab("tab6", jButton4);

        programacionMainFrame.addTab("Programacion", programacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ejercicio 1", jPanel1);

        jTabbedPane3.addTab("Álgebra Booleana", jTabbedPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Factorial de ‘n’ numero", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("CoFactorial de ‘n’ ", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Permutación y Combinación de ‘n’ ", jPanel4);

        jTabbedPane3.addTab(" Métodos de Conteo", jTabbedPane2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("De decimal a: hexadecimal y octal", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("De entero a binario y viceversa", jPanel7);

        jTabbedPane3.addTab("Sistemas Numéricos", jTabbedPane6);

        programacionMainFrame.addTab("Mate. Discretas", jTabbedPane3);
        programacionMainFrame.addTab("tab3", jTabbedPane4);
        programacionMainFrame.addTab("tab4", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(programacionMainFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(programacionMainFrame)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int randomNumber = (int )Math.ceil(Math.random() * 10);

        pt3TextArea.setText("\n" + randomNumber);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int cadena = pt2TextField.getText().length();
        JOptionPane.showMessageDialog(null,"La longitud del texto es: " +cadena, "Longitud de la cadena", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pt1ResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt1ResultButtonActionPerformed

        String opt = pt1ComboBox.getSelectedItem().toString();
        if(opt == "Triángulo"){

            if(pt1CheckBox.isSelected()){
                int baseValue = Integer.parseInt(pt1BaseTextField.getText());
                int alturaValue = Integer.parseInt(pt1AlturaTextField.getText());
                JOptionPane.showMessageDialog(null, "El area del triangulo es: " + (baseValue*alturaValue)/2, "Base del triangulo",  JOptionPane.INFORMATION_MESSAGE);
            }else {
                int baseValue = Integer.parseInt(pt1BaseTextField.getText());
                int alturaValue = Integer.parseInt(pt1AlturaTextField.getText());
                JOptionPane.showMessageDialog(null, "El area del triangulo es: "+(int)(baseValue*alturaValue)/2, "Base del triangulo",  JOptionPane.INFORMATION_MESSAGE);
            }
        }else if(opt == "Círculo"){

            if(pt1CheckBox.isSelected()){
                int radioValue = Integer.parseInt(pt1RadioTextField.getText());
                double result = (Math.PI* (radioValue * radioValue));
                JOptionPane.showMessageDialog(null, "El area del circulo es: " + result, "Radio del circulo", JOptionPane.INFORMATION_MESSAGE);
            }else {
                int radioValue = Integer.parseInt(pt1RadioTextField.getText());
                double result = (Math.PI* (radioValue * radioValue));
                JOptionPane.showMessageDialog(null, "El area del circulo es: "+(int)result, "Radio del circulo", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_pt1ResultButtonActionPerformed

    private void pt1ComboBoxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt1ComboBoxbtnActionPerformed
        String opt = pt1ComboBox.getSelectedItem().toString();
        if(opt == "Triángulo"){
            pt1BaseLabel.setVisible(true);
            pt1AlturaLabel.setVisible(true);
            pt1BaseTextField.setVisible(true);
            pt1AlturaTextField.setVisible(true);
            pt1ResultButton.setVisible(true);
        }else if(opt == "Círculo"){
            pt1RadioLabel.setVisible(true);
            pt1RadioTextField.setVisible(true);
            pt1ResultButton.setVisible(true);

        }
    }//GEN-LAST:event_pt1ComboBoxbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void pt4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt4ButtonActionPerformed
        double num = Math.sqrt(Integer.parseInt(pt4Label.getText()));
        JOptionPane.showMessageDialog(null,"La raiz cuadrada del numero es: " + num , "Raiz Cuadrada",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pt4ButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           int num1 = Integer.parseInt(ptt1TextField1.getText());
           int num2 = Integer.parseInt(ptt1TextField2.getText());
           int num3 = Integer.parseInt(ptt1TextField3.getText());
           
           if(num1 == num2 && num1 == num3) {
               JOptionPane.showMessageDialog(null, "Todos son numeros iguales" ,"Numeros iguales",JOptionPane.INFORMATION_MESSAGE);
           }else if(num1 > num2){
               if(num1 == num3){
                   JOptionPane.showMessageDialog(null, num1 + " y " + num3 + " son numeros iguales" ,"Numeros iguales",JOptionPane.INFORMATION_MESSAGE);
               }else if(num1 > num3){
                   JOptionPane.showMessageDialog(null, "El numero mayor es: " + num1,"Numero Mayor",JOptionPane.INFORMATION_MESSAGE);
               }
           }
               else if(num1 == num2){
                   JOptionPane.showMessageDialog(null,num1 + " y " + num2 + " son numeros iguales" ,"Numeros iguales",JOptionPane.INFORMATION_MESSAGE);
               }else if(num2 > num3){
                   JOptionPane.showMessageDialog(null, "El numero mayor es: " + num2,"Numero Mayor",JOptionPane.INFORMATION_MESSAGE);
               }else if(num3 > num2){//Se que esto parece que no tiene sentido pero lo tiene
                   JOptionPane.showMessageDialog(null, "El numero mayor es: " + num3,"Numero Mayor",JOptionPane.INFORMATION_MESSAGE);
               }
               else if(num2 == num3){
                   JOptionPane.showMessageDialog(null, num2 + " y " + num3 + " son numeros iguales" ,"Numeros iguales",JOptionPane.INFORMATION_MESSAGE);
               }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void pt22Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt22Button1ActionPerformed
          String edad = ptt22TextField1.getSelectedItem().toString();
          System.out.println(edad);
          if(edad == "Mayor a 60"){
              JOptionPane.showMessageDialog(null, "Eres un anciano" ,"Tu etapa de vida",JOptionPane.INFORMATION_MESSAGE); 
          }else if(edad == "Mayor a 26"){
              JOptionPane.showMessageDialog(null, "Eres un adulto" ,"Tu etapa de vida",JOptionPane.INFORMATION_MESSAGE);
          }else if(edad == "Mayor a 17"){
              JOptionPane.showMessageDialog(null, "Eres un adulto joven" ,"Tu etapa de vida",JOptionPane.INFORMATION_MESSAGE);
          }else if (edad == "Mayor a 11"){
              JOptionPane.showMessageDialog(null, "Eres un adolecente" ,"Tu etapa de vida",JOptionPane.INFORMATION_MESSAGE);
          }else if(edad == "Mayor a 4"){
              JOptionPane.showMessageDialog(null, "Eres un infante" ,"Tu etapa de vida",JOptionPane.INFORMATION_MESSAGE);
          }else if(edad == "Menor a 4"){
              JOptionPane.showMessageDialog(null, "Eres un bebe" ,"Tu etapa de vida",JOptionPane.INFORMATION_MESSAGE); 
          }
    }//GEN-LAST:event_pt22Button1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String text = pt25TextField1.getText();
        int acumm = 0;
        
       for(int i = 0, j = 1; j <= text.length(); i++, j++){
           for(int k = 0, l = 1; l <= text.length(); l++, k++){
               if(text.substring(k,l).equals("j") || text.substring(k,l).equals("J")){
                   acumm = acumm + 1;
                   if(l == text.length()){
                       j = text.length();
                       if(j == text.length()){
                           JOptionPane.showMessageDialog(null, "El texto tiene " + acumm + " J","Resultado", JOptionPane.INFORMATION_MESSAGE);
                       }
                   }
               }
               
           }
           if(acumm == 0 ){
               JOptionPane.showMessageDialog(null, "No hay ninguna J en el texto" , "Resultado", JOptionPane.INFORMATION_MESSAGE);
               j = text.length();
           }
       }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void pt23Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt23Button1ActionPerformed
        String text = pt23TextField1.getText();
        switch(text){
            case "0":
                JOptionPane.showMessageDialog(null, "Uno", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "1": 
                JOptionPane.showMessageDialog(null, "Uno", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "2":
                JOptionPane.showMessageDialog(null, "Dos", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "3":
                JOptionPane.showMessageDialog(null, "Tres", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "4":
                JOptionPane.showMessageDialog(null, "Cuatro", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "5":
                JOptionPane.showMessageDialog(null, "Cinco", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "6":
                JOptionPane.showMessageDialog(null, "Seis", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "7":
                JOptionPane.showMessageDialog(null, "Siete", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "8":
                JOptionPane.showMessageDialog(null, "Ocho", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "9":
                JOptionPane.showMessageDialog(null, "Nueve", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            case "10":
                JOptionPane.showMessageDialog(null, "Diez", text, JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Ingresa un numero del 0  al 10", text, JOptionPane.INFORMATION_MESSAGE);
                       
                       
                                                            
                
                                  
        }
    }//GEN-LAST:event_pt23Button1ActionPerformed

    private void pt4LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt4LabelActionPerformed
            int base = Integer.parseInt(pt31TextField1.getText());
         
    }//GEN-LAST:event_pt4LabelActionPerformed

    private static void timer(){
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
          int base = Integer.parseInt(pt31TextField1.getText());
          JTextArea texto = new JTextArea(10,40);
          if(pt31CheckBox.isSelected()){
              int lim = Integer.parseInt(pt31TextFiel2.getText());
              for(int i = 1; i <= lim; i++){
                  String text = base +" x " + i + " = " + base*i;
                  prueba.append("\n " + text);
              }
          }else {
              for(int i = 1; i < 11; i++){
                  String text = base +" x " + i + " = " + base*i;
                  prueba.append("\n " + text);
              }
          }
        
          
    }//GEN-LAST:event_jButton10ActionPerformed

    private void pt31TextFiel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt31TextFiel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pt31TextFiel2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(pt31CheckBox.isSelected()){
              pt31LimLabel.setVisible(true);
              pt31TextFiel2.setVisible(true);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
           int anio = Integer.parseInt(pt32TextField1.getText());
           
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        prueba.setText(null);
    }//GEN-LAST:event_jButton13ActionPerformed


    private void txtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField1ActionPerformed
        // TDO add your handling code here:ss
    }//GEN-LAST:event_txtField1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        
        
        int ola = Integer.parseInt(textField1.getText());
           int ola2 = Integer.parseInt(textField2.getText());
           JOptionPane.showMessageDialog(null,ola + ola2, "Suma",JOptionPane.INFORMATION_MESSAGE);
    }
    private void jButtonParImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParImparActionPerformed
          
       int num = Integer.parseInt(txtField1.getText());
       
        for(int i = 0 ; i<=num ; i++){
            if(i%2 == 0 ){
                txtArea1.append(i + " Numero Par \n" );
            }else if(i%2 != 0){
                txtArea1.append(i + " Numero Impar \n" );
            }
        }
    }//GEN-LAST:event_jButtonParImparActionPerformed

    private void arrt1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrt1Button1ActionPerformed
            //int arrayLength = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la longitud del arreglo"));
            int arrayLength = Integer.parseInt(arrt1TextField1.getText());
            int[] arreglo = new int[arrayLength];
            for(int i = 0; i <= arrayLength -1 ; i++){
                int value = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero " + (i + 1)));
                arreglo[i] = value;
            }
            int b = 0;
            for(int a = 0; a < arreglo.length; a++){
                if(arreglo[a] > b){
                    b = arreglo[a];
                }
            }
            JOptionPane.showMessageDialog(null, "El numero mayor es : " + b, "Numero mayor",JOptionPane.INFORMATION_MESSAGE);
            
            
           
            
    }//GEN-LAST:event_arrt1Button1ActionPerformed

    private void arrt1TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrt1TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrt1TextField1ActionPerformed

    private void pt25TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt25TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pt25TextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane arreglos;
    private javax.swing.JButton arrt1Button1;
    private javax.swing.JTextField arrt1TextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonParImpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane poo;
    private javax.swing.JTabbedPane programacion;
    private javax.swing.JTabbedPane programacionMainFrame;
    private javax.swing.JTabbedPane programasCondicionales;
    private javax.swing.JTabbedPane programasRepetitivos;
    private javax.swing.JTabbedPane programasSecuenciales;
    private javax.swing.JTextArea prueba;
    private javax.swing.JLabel pt1AlturaLabel;
    private javax.swing.JTextField pt1AlturaTextField;
    private javax.swing.JLabel pt1BaseLabel;
    private javax.swing.JTextField pt1BaseTextField;
    private javax.swing.JCheckBox pt1CheckBox;
    private javax.swing.JComboBox<String> pt1ComboBox;
    private javax.swing.JButton pt1ComboBoxbtn;
    private javax.swing.JPanel pt1Ejercicio1;
    private javax.swing.JPanel pt1Ejercicio2;
    private javax.swing.JPanel pt1Ejercicio3;
    private javax.swing.JPanel pt1Ejercicio4;
    private javax.swing.JPanel pt1Ejercicio5;
    private javax.swing.JLabel pt1RadioLabel;
    private javax.swing.JTextField pt1RadioTextField;
    private javax.swing.JButton pt1ResultButton;
    private javax.swing.JButton pt22Button1;
    private javax.swing.JButton pt23Button1;
    private javax.swing.JTextField pt23TextField1;
    private javax.swing.JTextField pt25TextField1;
    private javax.swing.JPanel pt2Ejercicio1;
    private javax.swing.JPanel pt2Ejercicio2;
    private javax.swing.JPanel pt2Ejercicio3;
    private javax.swing.JPanel pt2Ejercicio4;
    private javax.swing.JTextField pt2TextField;
    private javax.swing.JCheckBox pt31CheckBox;
    private javax.swing.JLabel pt31LimLabel;
    private javax.swing.JTextField pt31TextFiel2;
    private javax.swing.JTextField pt31TextField1;
    private javax.swing.JTextField pt32TextField1;
    private javax.swing.JTextField pt3TextArea;
    private javax.swing.JButton pt4Button;
    private javax.swing.JTextField pt4Label;
    private javax.swing.JTextField ptt1TextField1;
    private javax.swing.JTextField ptt1TextField2;
    private javax.swing.JTextField ptt1TextField3;
    private javax.swing.JComboBox<String> ptt22TextField1;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextArea txtArea1;
    private javax.swing.JTextField txtField1;
    // End of variables declaration//GEN-END:variables
}
